##  -*-  coding: utf-8; mode: ruby -*-  ##
##  vi: set ft=ruby

Vagrant.configure("2") do |config|
  config.vm.box = "takahiro-itou/ubuntu-jammy64-develop"

  config.vm.provider "virtualbox" do |v|
    v.name   = "vagrant-ubuntu-develop"
    v.memory = "3072"

    v.customize [
      "modifyvm",               :id,
      "--mouse",                "usbtablet",
      "--graphicscontroller",   "vmsvga",
    ]

    v.gui    = false
  end

  config.vm.network(:forwarded_port, guest: 22, host: 11022, id: "ssh")
  config.vm.network("private_network", ip: "192.168.33.10")
  config.vm.synced_folder(".", "/vagrant", disabled: true)
end

load  File.expand_path('common/CommonCustomize.rb')

$disk_image_file = File.expand_path('./disk/ubuntu-develop-sdc.vdi')
load  File.expand_path('common/AttachSCSIHdd.rb')

# Provisioning(s)
load  File.expand_path('common/UploadFiles.rb')
load  File.expand_path('common/SetupUbuntu.rb')
load  File.expand_path('common/RamDisk.rb')
load  File.expand_path('common/SetupUsers.rb')
